### ISSUE TITLE
ENOSPC in file.go

### ISSUE THREAD

**Issue by larsks** [purpleidea/mgmt#1]
We talked about this, but because the question is in the source:

			} else if err == syscall.ENOSPC {
				// XXX: i sometimes see: no space left on device
				// XXX: why causes this to happen ?
				log.Printf("Strange file[%v] error: %+v\n", obj.Name, err.Error) // 0x408da0
				log.Fatal(err)
			} else {

The `ENOSPC` error happens when the system runs out of available inotify watches, a limit that is controlled by the `fs.inotify.max_user_watches` sysctl (which defaults to 8192).  I run backup software that uses inotify for filesystem monitoring, and in these environments I often crank that value way up:

    sysctl -w fs.inotify.max_user_watches=819200

**Comment by purpleidea** [comment]
@larsks Interesting, now at least I know what that error could mean... What's confuses me, is I never had anywhere *near* 8192 at a single time... Does this indicate a leak? In my code? In the lib? Or something else entirely...

**Comment by larsks** [comment]
It could just indicate that your tool isn't the only consumer of inotify resources on the system.  Coincidentally, I asked about diagnosing this sort of thing a few years ago [here](http://unix.stackexchange.com/questions/15509/whos-consuming-my-inotify-resources) and some of the answers seem useful.

**Comment by fujin** [comment]
Anecdotally we (@pantheon-systems) have found that inotify is generally unusable / to be avoided at any real scale (identified first in an unrelated golang on-access resident malware scanner) and switched our system to the new fanotify API instead. Especially worse is other non-controlled parts of the system making use of inotify as part of day to day operations are impacted by this global constrained resource (num-of-watches). Even worse is having to use a watch to track a directory then handle child elements non-recursively (intensive path walking). You can basically cripple a system where any user code is also using inotify with this type of behavior.

I wanted to log a fault here after reading your blog post (great article by the way!) but a colleague pointed me at this one already :) I'd definitely suggest the Kernels' fanotify API. I used https://bitbucket.org/madmo/fanotify to wrap it.

My suggestion would definitely be to not use inotify.

**Comment by fujin** [comment]
Oh.. sorry for the necro. :(

**Comment by purpleidea** [comment]
@fujin This here is my favourite point:

> other non-controlled parts of the system making use of inotify as part of day to day operations are impacted

I fully agree and hope to switch to fanotify in the future, however at the moment, just getting the basic plumbing right (and not scaling) is the priority. In fact, I actually didn't even implement the recursive directory watching yet because of precisely this issue, and the fact that (in agreement with you) fanotify would be a better solution.

Any chance you're interested in perhaps adding fanotify support to the https://github.com/go-fsnotify/fsnotify library? I think that would perhaps be the best way to consume it, so that:
1) We can fallback to inotify on older systems
2) In theory we'd be able to eventually support yucky things like Windows and OSX ;)

In case you're interested in that scenario, I've opened an issue to ask the maintainers what they think: https://github.com/go-fsnotify/fsnotify/issues/114

Cheers!

**Comment by purpleidea** [comment]
PS: Not necro, just @larsks got in early when I first started writing the inotify part.

FWIW, I plan to cause the ENOSPC detection to trigger an error in the file type. The error will be usefully propagated upwards once I've added better error handling to mgmt! (shh, I didn't tell anyone it was missing yet...)

**Comment by purpleidea** [comment]
This is now fixed with the built-in error handling. A meta-parameter to downgrade to polling after N general failures could be welcome, for example, but that is out of scope here.
