### ISSUE TITLE
Why affero license? It's very toxic to corporate adoption due to virality.

### ISSUE THREAD

**Issue by countspongebob** [purpleidea/mgmt#212]
## Versions:

* mgmt version (eg: `mgmt --version`):

* operating system/distribution (eg: `uname -a`):

* golang version (eg: `go version`):

**Comment by roidelapluie** [comment]
I do agree with that.

**Comment by purpleidea** [comment]
Hi @countspongebob,

Here is some history and background. Read this with the knowledge that mgmtconfig has been designed to be especially friendly to corporations where we think much of the adoption will be.

#### History (my perspective/interpretation, not speaking for anyone else):
I and others used to be major puppet users. Back in those days, puppetlabs decided to make a lot of their once all open source tech, proprietary. Many felt betrayed by this. They were struggling to actually make a profit, and they felt that was the best way forward. That was their decision and that's fine by me.

I'm currently fortunate that my employer (AFAIK) has no intention of following the open core model. In discussion with many community folks about their preferred license, we chose AGPL because:

* It was a community promise that we wouldn't take their contributions proprietary, thus negating the investment they put into the project

* It actually doesn't matter for the config management use case. Why? Anyone using a config management tool in their own infrastructure privately isn't obliged to release *any* changes to the rest of the world. Even with a load of proprietary changes or add-ons! It only "blocks" someone trying to offer proprietary config-management-as-a-service, which is something that isn't even sane AFAIK.

This last point is even covered in the GPL FAQ: https://www.gnu.org/licenses/gpl-faq.html#InternalDistribution

Hopefully this alleviates your concerns, happy to talk more offline if there's something we can do to make this easier for you, or hear some specific points where this blocks you. I'm github username at gmail

**Comment by purpleidea** [comment]
Btw, @countspongebob Do you think GPLv3 has the same problems or not?

**Comment by purpleidea** [comment]
For closure, I thought you should know that we switched to GPL https://github.com/purpleidea/mgmt/commit/46be83f8f79c8cb81fdf1eae9d951c70c69246b4 Happy hacking

**Comment by countspongebob** [comment]
Switching to GPLv3 takes the discussion from "no way", to "it's complicated". This would require us to be precise about how/when/where we would use something (ahead of actually understanding our technical designs), understanding precisely how GPLV3 is linked and operated, understanding estoppel, involving legal resources in analysis of the situation, etc.

This is too high a barrier for many larger corporate groups, and would generally be too high a bar for me to cross if I were, say, CTO of a startup as well.

**Comment by roidelapluie** [comment]
GPLv3 is pretty well known by companies ; better than AGPL. It is still clear that there is a gap between mgmt and its core componenents -- e.g. etcd (apache 2) but for most of the companies GPLv3 is fine for config management tool.

**Comment by purpleidea** [comment]
@countspongebob Sorry that it's complicated, that's not the goal. It was always supposed to be about the tech.

In case it's not abundantly clear, the GPL (either V2, V3 or AGPLv3) does NOT apply to *code* or config that you write and that mgmt runs. In fact it's perfectly fine for you to run proprietary code with it, in the same way that Ansible is okay with this. (Same license as mgmt now.)

In discussions with some other interested corporate contributors they were okay with GPL.

If there are any legal related technical questions about mgmt you'd like answer, LMK.

Thanks
