### ISSUE TITLE
Linux only ?

### ISSUE THREAD

**Issue by joeblew99** [purpleidea/mgmt#213]
This is nice for managing desktops also.
From looking SVC for example this looks like it's only designed for Linux ?

**Comment by purpleidea** [comment]
@joeblew99 We barely have enough resources to sustain the project as is. Linux and systemd is the only platform I'm targeting, because it's the only one I personally care about, but if you'd like to add equivalent svc backends for different platforms or svc managers, patches are welcome.

I'm going to close this since it's a question, but feel free to open a new issue to discuss a specific patch for a backend if you'd like to.
