### ISSUE TITLE
mgmt on Mesos?

### ISSUE THREAD

**Issue by h12w** [purpleidea/mgmt#3]
The [DAG picture](https://ttboj.files.wordpress.com/2016/01/graph1.png) shown on your blog looks very similar to a [Hadoop/Spark DAG](http://image.slidesharecdn.com/mapreducevsspark-150512052504-lva1-app6891/95/map-reduce-vs-spark-17-638.jpg?cb=1431408380). Will it be reasonable if mgmt becomes a framework running on [Mesos](http://mesos.apache.org/)?

**Comment by purpleidea** [comment]
@h12w This is an interesting question that I do not currently have an answer for, partially because I am not an expert on mesos. If you are, or know of people who would like to discuss this, then I'm happy to participate when time allows.

One disclaimer, I personally don't have any time to devote to patching mgmt/mesos to work together, but I am happy to review and receive contributions from the community, and take into account any design elements that will make it as friendly as possible to achieve what you want to build.

HTH

**Comment by purpleidea** [comment]
@h12w I haven't heard anything, so I'm going to close this for now. If you want to discuss in the future, and want to write a patch, please ping me, or open a new issue. Thanks!

**Comment by h12w** [comment]
OK, thanks.

I am not a Mesos expert, but after listening to an interview of [Ben Hindman](http://www.se-radio.net/2015/08/se-radio-episode-235-ben-hindman-on-apache-mesos/), I realized that all distributed systems can share a Mesos like kernel. No mather it is a cron job executor (Chronos), cluster manager (Aurora) or stream processer (Spark). So I guess a distributed configuration management tool can also benefit from Mesos.

**Comment by purpleidea** [comment]
@h12w We'll have to revisit this in the future. Cheers!
