### ISSUE TITLE
have `run --lang` accept a directory argument

### ISSUE THREAD

**Issue by aequitas** [purpleidea/mgmt#305]
Coming back to my idea of an include statement. Having a directory with a file organisation is nice to have. Since the language is declarative file load order should be irrelevant. Hence maybe it is an idea to have mgmt accept a directory for `--lang` as well and have it recurse for `*.mcl` files that will be combined into the `start.mcl` file before copying it here https://github.com/purpleidea/mgmt/blob/b19583e7d35edaad1705d35f00852ec03486750b/lang/gapi.go#L75.

I don't know if you have a different direction planned for this otherwise I'd be glad to dive into it.

**Comment by purpleidea** [comment]
@aequitas Here's what I know:

I still need to implement a notion of singletons and `ExprFunc` values in the language. There are some other missing pieces too. With these will come some notion of modules...

I haven't decided whether we should require some sort of explicit directory structure or not. Discussion is welcome here.

Lastly, for the compiler to work properly, we essentially combine all of the files into a big string and lex/parse it all together. There might be a more clever way of lexing/parsing each individually and then combining them at a later stage, but I haven't thought about it much.

If accepting a directory interests you, then please go for it :) One heads up: you'll have to recursively build the output in a deterministic, non-fs-specific way, so that repeated compiles order similarly. later on we might also want to store the file order and lengths so that we can backtrack to figure out what file and line number an error happened on.

Thanks!

**Comment by purpleidea** [comment]
The whole import/modules and running from a dir is WIP, part of which is implemented in the feat/import branch, and part of which is coming soon. The behaviour: if you pass mgmt a dir, it will search for a metadata.yaml entry point, and if it doesn't find that it will look for main.mcl

Coming soon, so closing this.
