### ISSUE TITLE
[LOVE] Add a mount resource

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#314]
#### Welcome:

This is a intermediate level patch for someone who has some experience in golang, and who is new to mgmt. It is meant to encourage new programmers to get involved with mgmt. It will probably take you at least a day or so to complete.

#### Intro:

Mgmt has a number of resources. We'd like for you to add one more. We'd like to have a "mount" resource which can mount or unmount.
To implement this, you'll need to either recommend an alternate design, or use the one provided below.

#### Design:

Systemd provides a very powerful mount facility which (AIUI) can provide events about mounts. The goal should be to wrap this facility so that we can benefit from the power of the mount mechanics that systemd has built.
You might consider re-using some of the `svc` code as was done in the `nspawn` resource.
More research into the mechanics of how this should work should be discussed in this issue before this is implemented.

Read the contributing tips:
https://github.com/purpleidea/mgmt/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Happy hacking, and ping me for questions!

#### Bonus/Future work:

* Write a few tests.
* Recommend some other parameters that could be added.
* Add some automatic edges to other resources.
* Consider whether we can be clever about adding autoedges in situations when something happens in a mount (nested mounts?, managed file/directory paths in a mount?, exec's running from a mount? other?) which would require a specific order to run in.
* Consider whether send/recv makes sense for this resource and implement in a later patch.

**Comment by jonathangold** [comment]
@purpleidea purpleidea I'd like to use the signal from `/org/freedesktop/UDisks2` rather than from `/org/freedesktop/DBus/systemd1` due to the contents of the message, and signal to noise ratio (lots of events to filter with systemd1.) To illustrate, here is the result of `mount /home/jon/isotest.iso /home/jon/iso`

Here are the signals captured from systemd1 (just UnitNew messages):
`signal time=1524196075.479047 sender=:1.0 -> destination=(null destination) serial=541 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "sys-devices-virtual-block-loop0.device"
   object path "/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop0_2edevice"
`

`
signal time=1524196075.479055 sender=:1.0 -> destination=(null destination) serial=542 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "dev-disk-by\x2dlabel-CDROM.device"
   object path "/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2dlabel_2dCDROM_2edevice"
`

`
signal time=1524196075.479064 sender=:1.0 -> destination=(null destination) serial=543 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "dev-disk-by\x2duuid-2018\x2d04\x2d07\x2d17\x2d59\x2d01\x2d00.device"
   object path "/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2duuid_2d2018_5cx2d04_5cx2d07_5cx2d17_5cx2d59_5cx2d01_5cx2d00_2edevice"
`

vs the signal from UDisks2 (storaged):
`
signal time=1524197758.177812 sender=:1.3 -> destination=(null destination) serial=50 path=/org/freedesktop/UDisks2; interface=org.freedesktop.DBus.ObjectManager; member=InterfacesAdded
   object path "/org/freedesktop/UDisks2/block_devices/loop0"
   array [
      dict entry(
         string "org.freedesktop.UDisks2.Filesystem"
         array [
            dict entry(
               string "MountPoints"
               variant                   array [
                     array of bytes "/home/jon/iso" + \0
                  ]
            )
            dict entry(
               string "Size"
               variant                   uint64 0
            )
         ]
      )
   ]
`
As you can see, the storaged signal encodes the mountpoint in a []byte, which would make filtering much simpler, if needed. If we stick with systemd1, then it would require unescaping the message and then resolving the file that backs the loop device as well as any symlinks, since it doesn't contain the filename, or the mountpoint as it stands. The code would be much simpler with UDisks2.

**Comment by purpleidea** [comment]
My gut feeling is that UDisks2/Storaged just does some very simple processing based on the data from systemd1. So if it's just that, then we should just do the same processing ourselves. If it's providing something additional, then we should learn what that is first. Adding the dependency on this extra daemon doesn't make sense if there's no clear value, and in particular would make this resource unusable for anyone without that daemon.

For example, on a recent fedora+GUI install I see:

```
$ ps auxww | grep -i udisk
james     2545  0.0  0.0 576012  1676 ?        SLsl Mar09   0:22 /usr/libexec/gvfs-udisks2-volume-monitor
root      2557  0.0  0.0 584416  4456 ?        SLsl Mar09   1:01 /usr/libexec/udisks2/udisksd
```

On a modern headless centos7 I see:

```
ps auxww | grep -i udisk
<nothing>
```

So am I grepping for the right, or is it not present on headless machines? Should it be?

**Comment by jonathangold** [comment]
You're right, it isn't on minimal centos. Looks like I missed one useful signal in the above systemd1 capture, which has the (escaped) mount point. Should be pretty straightforward to implement.

**Comment by purpleidea** [comment]
I think we can close this. w00t!
