### ISSUE TITLE
Separation of concerns using plugins or compile time options

### ISSUE THREAD

**Issue by nwmcsween** [purpleidea/mgmt#366]
If mgmt ever grows beyond Linux or supports multiple implementations of any software it will need to either gain a compile time option support or a plugin system.

**Comment by purpleidea** [comment]
I have a design (currently offline) for pluggable resources, functions and other aspects using golang's dlopen (`plugin`). I allude to it in the FAQ's.

I'm not planning on working on this for a while, but if you'd like to build this, happy to share the design and review your patches!

I'm going to close this since it's not an open issue that we can act on, and more of commentary. Join us on the mailing list or on IRC for that sort of thing :)
