### ISSUE TITLE
Embedding etcd into an existing golang project ,And is a cluster.

### ISSUE THREAD

**Issue by 332000640** [purpleidea/mgmt#488]
Sorry for asking questions on etcd in this project. I hope you can help me.    I tried this example at https://godoc.org/github.com/coreos/etcd/embed and changed some parameters. I don't know how to build a distributed cluster. Can I have a more detailed example? I also read this https://github.com/etcd-io/etcd/issues/3670 question, I still don't know how to start. If you embed etcd in my program and form a three-node cluster.

**Comment by purpleidea** [comment]
> Sorry for asking questions on etcd in this project. I hope you can help me.

Only to a limited extent for free, since I'm working on this project instead of getting income.

> I tried this example at https://godoc.org/github.com/coreos/etcd/embed and changed some parameters. I don't know how to build a distributed cluster. Can I have a more detailed example?

It's not trivial. If you want to do it with golang, it's quite complicated. We aim to solve this problem in mgmt for you automatically. I'm actually rewriting some of this code as we speak.

> I also read this etcd-io/etcd#3670 question, I still don't know how to start. If you embed etcd in my program and form a three-node cluster.

Here are your options:
0) Avoid solving it and just use mgmt to do it for you.
1) You can look at the existing (bad) code I've written and try and learn from that.
2) You can wait until the improved good code is out and try and learn from that.
3) You can try and learn on your own
4) You can try to hire me for some consulting
5) ?

I'm sorry I can't help you more, but I have no idea who you are, and this isn't related to mgmt.
