### ISSUE TITLE
[LOVE] Input files as positional arguments

### ISSUE THREAD

**Issue by wdullaer** [purpleidea/mgmt#502]
## Description:
At the moment input files are specified in a command line flag: eg `mgmt run lang --lang some-file.mcl`. 

It is more common for input files to be handled as positional arguments: eg `mgmt run lang some-file.mcl`
It should make the tool a bit easier to use.

I'm happy to hack on this when I get a bit of spare time.

**Comment by purpleidea** [comment]
Sounds good! Let us know when you have a PR ready.

**Comment by purpleidea** [comment]
I have two or three pending blog posts that I'm working on, and I think it would be fantastic to get this feature merged for the next release (0.0.20) and also so that the blog posts can use the new syntax. Any chance you've had some cycles to work on it or think that you'll have some time to do it this week?

Thanks!

**Comment by wdullaer** [comment]
I'm not sure if I'll be able to spend a lot of time on this the next week.

It's a pretty busy period. I'll ping you on IRC if I should start on it.

**Comment by ahmedsharif865** [comment]
Is someone still working on this issue?

**Comment by purpleidea** [comment]
@ahmedsharif865 This is actually already fixed. If you're looking for something to work on, please let me know. There are other things that don't have open issues too! Thanks!
