### ISSUE TITLE
mismatched types gopkg.in/fsnotify.v1

### ISSUE THREAD

**Issue by probonopd** [purpleidea/mgmt#561]
Getting `mismatched types "github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1".Op and "gopkg.in/fsnotify.v1".Op`.

Removing `github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1` would solve this.
On Travis CI with Ubuntu Xenial, getting:

```
$ go build -trimpath -ldflags="-s -w" github.com/probonopd/appimage/src/appimaged

# github.com/probonopd/appimage/src/appimaged

../../../go/src/github.com/probonopd/appimage/src/appimaged/inotify.go:47:20: invalid operation: event.Body.Op & "gopkg.in/fsnotify.v1".Write (mismatched types "github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1".Op and "gopkg.in/fsnotify.v1".Op)

../../../go/src/github.com/probonopd/appimage/src/appimaged/inotify.go:47:70: invalid operation: event.Body.Op & "gopkg.in/fsnotify.v1".Create (mismatched types "github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1".Op and "gopkg.in/fsnotify.v1".Op)

../../../go/src/github.com/probonopd/appimage/src/appimaged/inotify.go:53:20: invalid operation: event.Body.Op & "gopkg.in/fsnotify.v1".Remove (mismatched types "github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1".Op and "gopkg.in/fsnotify.v1".Op)

../../../go/src/github.com/probonopd/appimage/src/appimaged/inotify.go:53:72: invalid operation: event.Body.Op & "gopkg.in/fsnotify.v1".Rename (mismatched types "github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1".Op and "gopkg.in/fsnotify.v1".Op)
```

References:
* https://github.com/probonopd/appimage/blob/cb770fa039b4002e1b2b6ed10d8634b5cd16e854/.travis.yml
* https://travis-ci.com/probonopd/appimage/jobs/252132720#L267

**Comment by purpleidea** [comment]
@probonopd I think I'm missing a tiny bit of context of what you're trying to do... Our builds don't seem to hit this issue...

As a side-note, I should disclose that we vendored an older version of fsnotify, because a while back a newer version broke all our builds, and we haven't taken the time to write enough tests and bump to a newer version. (That task is open for anyone willing.)

**Comment by probonopd** [comment]
In my code, I need to check whether incoming notifications are of a certain type:

```
if event.Body.Op&fsnotify.Write == fsnotify.Write || event.Body.Op&fsnotify.Create == fsnotify.Create {
...
```

https://github.com/probonopd/appimage/blob/5b3924784ca4a7cae5e1549031ca3ed4ef4c8de5/src/appimaged/inotify.go#L14

To be able to do this comparison, (I think) I need to import `fsnotify`:

```
import (
(...)
	"gopkg.in/fsnotify.v1"
)
```

https://github.com/probonopd/appimage/blob/5b3924784ca4a7cae5e1549031ca3ed4ef4c8de5/src/appimaged/inotify.go#L45

Golang won't let me include the vendored `fsnotify.v1` directory outside of a `$GOPATH`. Hence I need to include the upstream one. Now I have two, one included from my code and one included from your code (the vendored one). They conflicting.
I can only get the code to compile if I do

```
go get github.com/probonopd/appimage/src/appimaged || true # This fails
rm -rf $GOPATH/src/github.com/purpleidea/mgmt/vendor/gopkg.in/fsnotify.v1
go build -trimpath -ldflags="-s -w" github.com/probonopd/appimage/src/appimaged
```

https://github.com/probonopd/appimage/blob/5b3924784ca4a7cae5e1549031ca3ed4ef4c8de5/.travis.yml#L37-L40

Please advise.

**Comment by purpleidea** [comment]
@probonopd Can you explain how mgmt fits into all of this?? Are you importing it as a library for your code?? A bit of background knowledge would help a lot!

Solutions wise, I think there are two possibilities: (1) switch to the same vendored version we use. (2) We could unvendor fsnotify and switch to the git master version or a recent tag.

I actually prefer (2) since I think it would also solve your problem, however I think we need to do a bit of testing to make sure there aren't any bugs.

There might be a (3) but I'd need more information on what you're doing before I can recommend it.

HTH

**Comment by probonopd** [comment]
> Can you explain how mgmt fits into all of this??

I think

```
import (
(...)
	"gopkg.in/fsnotify.v1"
)
```

pulls it in. (2) sounds fine to me.

**Comment by purpleidea** [comment]
> I think "gopkg.in/fsnotify.v1" pulls it in.

What? No way.

**Comment by probonopd** [comment]
Sorry, I was confused. Meant to say: I think

import (
(...)
	"github.com/purpleidea/mgmt/recwatch"
)

pulls it in. I need recursive inotify.

**Comment by purpleidea** [comment]
@probonopd Ah, okay, in that case, I would recommend helping to write some tests and sending a patch to move mgmt to the git master version of fsnotify.

**Comment by purpleidea** [comment]
Going to close, but if you want to work on this for your needs, please send a patch. Thanks
