### ISSUE TITLE
[feat] Clean up on resource removal

### ISSUE THREAD

**Issue by rata** [purpleidea/mgmt#61]
Hi,

I was wondering if this solves some of the problems that chef doesn't.

For example, let's say I configure this to install package A and make sure that is run in one node. Then, let's say I remove that part of the "recipe" and just install package B (or just use a whole new "recipe" and stop using the other) and _then_ run it again. Will A still be there?

Or, is it possible (like with chef) to modify a "recipe" in a way that an already running node will run ok but it will fail on a new starting from scratch node? Or is there some way to make this impossible?

**Comment by rata** [comment]
@purpleidea thanks a lot! For the info and the welcoming attitude :)

I'm not sure there is a reasonable way to make something deterministic/reproducible, and somewhat "immutable", by just mutating things and when these things are complex and with side effects (like creating a file, checking with an external service and upon it's response do X or Y on the node, doing service discovery, etc.). Probably something that might help is a log fs, or something like that. But not sure it's worth it.

I think the best way is to have it always work from scratch is to make that the only way to change things (or do it often, at least), and make it fast and easy. In this sense, I think containers will solve the configuration management problem, powered with things like configmaps in kubernetes or similars.

But wanted to be sure if you had a nice solution to this (this is THE big problem of configuration managements tools, IMHO), I watched your presentation at coreOS via youtube and had a quick glance at the code and wasn't sure.

And thanks a lot, but I'm not interested in working on this now. As I've said, I'm not sure configuration management tools as we know them today solve what I consider the real problem, and containers seems like they do or have a better chance. But I'd love to be proven wrong and have to change my mind :)

**Comment by purpleidea** [comment]
On Sun, Sep 4, 2016 at 12:24 PM, rata <notifications@github.com> wrote:
>
> @purpleidea thanks a lot! For the info and the welcoming attitude :)

My pleasure!

> I think the best way is to have it always work from scratch is to make that the only way to change things (or do it often, at least), and make it fast and easy. In this sense, I think containers will solve the configuration management problem, powered with things like configmaps in kubernetes or similars.

Good luck with that!

> But wanted to be sure if you had a nice solution to this (this is THE big problem of configuration managements tools, IMHO), I watched your presentation at coreOS via youtube and had a quick glance at the code and wasn't sure.

I think there is more than one problem.

> And thanks a lot, but I'm not interested in working on this now. As I've said, I'm not sure configuration management tools as we know them today solve what I consider the real problem, and containers seems like they do or have a better chance. But I'd love to be proven wrong and have to change my mind :)

I think container technology is important, but it's a mistake to think
they're a replacement or in the same space as config management. Let's
keep this bug open for the legitimate feature request you made. If
you'd like to chat more, please just us in #mgmtconfig on Freenode.

Cheers!

**Comment by rata** [comment]
On Sun, Sep 04, 2016 at 01:46:54PM -0700, James wrote:
> I think container technology is important, but it's a mistake to think
> they're a replacement or in the same space as config management. Let's

I'm not saying it is a replacement. Just that it is not such an interesting
problem anymore, as a side effect :)

> keep this bug open for the legitimate feature request you made. If
> you'd like to chat more, please just us in #mgmtconfig on Freenode.

Sure, it's a legimite bug! I've just joined on IRC. Thanks a lot!

**Comment by purpleidea** [comment]
@rata Here's a good quote I like: https://twitter.com/purpleidea/status/772891832011284480

**Comment by rata** [comment]
@purpleidea sure, but it doesn't apply to what I've said :-)

**Comment by purpleidea** [comment]
@rata RE: 

> As I've said, I'm not sure configuration management tools as we know them today solve what I consider the real problem, and containers seems like they do or have a better chance. But I'd love to be proven wrong and have to change my mind :)

?

**Comment by rata** [comment]
On Mon, Sep 05, 2016 at 03:14:46PM -0700, James wrote:
> @rata RE: 
> 
> > As I've said, I'm not sure configuration management tools as we know them today solve what I consider the real problem, and containers seems like they do or have a better chance. But I'd love to be proven wrong and have to change my mind :)
> 
> ?

I think they have a better chance because of tools like kubernetes, with
configmaps, and they are reproducible from scratch always (as you need to always
create a new container, not modify an existing one).

**Comment by mildred** [comment]
I think this is a great problem to address in configuration management tools. This would be *the* killer feature that will make me use one tool over another.

Not on the same problem space, but there is terraform that handles this quite well. terraform is a tool to provision your cloud instances among other things, but I was thinking how we could add plugins to it so instead of launching machines in the cloud, it could manage a bare metal instance (yeah, I love bare metal).

Basically, it keeps in a state file what it did in the past. The state file contains the state of the infrastructure as it provisioned the nodes. If at one point you remove a resource from your code, it will detect that a resource existed (from the state file) and schedule its destruction.

We can do exactly that. I don't know yet the internals of mgmt but I suppose that the internal etcd cluster store can serve as this infrastructure state. When we remove a resource from the yaml file, I suppose a corresponding key is removed from the etcd cluster. We can watch this event and schedule the destruction of the resource (deletion of a file, removal of a package, a systemd unit, whatever)

We could even opt-in or opt-out of this mechanism for each resource. Just say `removal: explicit` or `removal: automatic` with possibly a configurable global default, and you're all set.

**Comment by purpleidea** [comment]
@mildred I'll have to think more about this, but I'll throw out some ideas for you to think about too. (Don't hold me to anything I'm saying here, it's just meant to get the ideas flowing...)

1a) I'm tempted by your idea of storing the state in etcd, but I'm also leaning towards having it be host specific and stored locally there in /var/... This is because if that resource made the change there, you'd want that reversibility info stored alongside it. This way, if the state is destroyed, we can assume the machine was too.

1b) I'll have to think about if I completely agree with this, but have a look at the `clean.sh` pattern I linked to in comment#2 and tell me if you like this rough approach (although implemented natively in golang in the resource).

2a) Let's talk about reversibility. Suppose you have a graph which does A->B->C. Now imagine you want to undo all of this. Would you want to follow the same order for the reverse operations or would you instead want to undo C->B->A? I'm leaning towards the latter.

2b) Implementation wise, we could add either a Cleanup/Reverse API, or include these operations as part of Close(), and I think it would be possible to run the graph in reverse fairly easily after nodes are removed.

2c) The tricky thing has to do with guaranteeing that we're in a known state if someone force kills the agent part way between the reverse operation of B->A, and how we would deal with this on subsequent runs. Should we cache the raw graph and make sure to run that first if we haven't finished cleaning up after it?

2d) One more interesting idea. What if we wanted to perform different graph transitions depending on different states. I'm working on building this into the engine. Here is some earlier work I did in puppet:
https://ttboj.wordpress.com/2013/09/28/finite-state-machines-in-puppet/ Naturally this is a big disaster because Puppet's engine isn't event based, but I think this will be very promising, in particular when our DSL is ready. As a result, do we really want to have reversible resources in all cases, or do we occasionally want to have different graphs which we execute depending on the previous state? (And some of those graphs might include pkg::state->uninstalled.

Looking forward to continuing the discussion and finishing some of the patches needed to get there!

Cheers
James

**Comment by mildred** [comment]
> 1a) [...] I'm also leaning towards having it be host specific and stored locally there in /var/ [...] This way, if the state is destroyed, we can assume the machine was too.

Yes, good idea. I admit I still haven't played with clustering in mgmt and all my use cases a pretty much single machines. But this is important.

> 1b) I'll have to think about if I completely agree with this, but have a look at the clean.sh pattern I linked to in comment#2 and tell me if you like this rough approach (although implemented natively in golang in the resource).

I think this is the general idea but I probably don't get it all. We do not necessarily want to remove all resources of some type that are not specified in mgmt. if the user did something manually unrelated to mgmt, we should't destroy it. I prefer if we track everything we did and then remove only those resources.

> 2a) Let's talk about reversibility. Suppose you have a graph which does A->B->C. Now imagine you want to undo all of this. Would you want to follow the same order for the reverse operations or would you instead want to undo C->B->A? I'm leaning towards the latter.

Probably C → B → A, you're right. You need to separate the vertices on the graph you are taking out, and take the edges that relates to the elements of that graph, and reverse them to clean things up.

> 2b) Implementation wise, we could add either a Cleanup/Reverse API, or include these operations as part of Close(), and I think it would be possible to run the graph in reverse fairly easily after nodes are removed.

That's what I saw in code. There is a place where we are taking out the vertices that were previously part of the graph and deleting them. Here we want to run the cleanup.

> 2c) The tricky thing has to do with guaranteeing that we're in a known state if someone force kills the agent part way between the reverse operation of B->A, and how we would deal with this on subsequent runs. Should we cache the raw graph and make sure to run that first if we haven't finished cleaning up after it?

It needs special care. Select first the vertice to clean up. Then run the cleanup and only after that you remove it from the graph and save this graph to disk. This way, if the machine shuts down at that moment, the vertice will still be part of the graph and will be cleaned up later. This needs to be done correctly.

> 2d) One more interesting idea. [...] As a result, do we really want to have reversible resources in all cases, or do we occasionally want to have different graphs which we execute depending on the previous state? (And some of those graphs might include pkg::state->uninstalled.

I don't grasp it all, and I don't know where this could be necessary. I don't understand how incompatible states could be represented n the same graph, but I'm having a too simplistic view of it perhaps. In any case, sometimes it is necessary to allow flexibility. This makes me think of the lifecycle property in terraform... With this, you can choose to make terraform ignore a change on a given property.

The best example for that is when you provision a machine in a cloud, and you specify the operating system image you want to install at first. The OS will be continuously update itself but terraform doesn't know that. The base OS image is still the old and outdated version. When you update your scripts to include a newer version, you don't want terraform to recreate your old machines that were based on an older image (but are kept up to date by other methods).

We need to have this kind of flexibility. This is kind of like you did in puppet-ipa where you can specify resources in puppet but allow them to be modified by the web-ui and not overwritten by puppet each time you redeploy.

**Comment by purpleidea** [comment]
This is mostly implemented in https://github.com/purpleidea/mgmt/commit/5c27a249b72f719396bcd5b33d743abd5172e51a

Only file supports this at the moment, but now that the engine parts and API all exist, it should be easy to add this for other resources.

What's missing: We don't add any edges, and after a while, if we think we want special edges added too, then we can think about what the interface for this should be.
