### ISSUE TITLE
implement a systemd-nspawn resource

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#70]
title says it all. help wanted :)

**Comment by fxleblanc** [comment]
# D-Bus API
In order to manage containers in the context of a resource, we could communicate using the D-Bus API provide by systemd-machined. I found some documentation in the machinectl source code that shows examples in C.
https://github.com/systemd/systemd/blob/bc3bb330b8543a31d4a1f488cb782b6ff3519d6a/src/machine/machinectl.c
# Other links
https://www.freedesktop.org/wiki/Software/systemd/machined/
https://godoc.org/github.com/guelfey/go.dbus

**Comment by purpleidea** [comment]
LGTM... @fxleblanc Are you working on this?

**Comment by fxleblanc** [comment]
@purpleidea Yes. I have some golang learning to do though. I'll keep you updated.

**Comment by purpleidea** [comment]
On Fri, Sep 30, 2016 at 10:09 AM, Félix Leblanc
<notifications@github.com> wrote:
>
> @purpleidea Yes. I have some golang learning to do though. I'll keep you updated.

Great! Ping us if you have questions!

**Comment by purpleidea** [comment]
The initial implementation of this is almost done in https://github.com/purpleidea/mgmt/pull/91
If anyone wants to have a final review before I merge, please LMK.

**Comment by daenney** [comment]
So since #91 is merged, close this? Or detail what the follow up should be?

**Comment by purpleidea** [comment]
@daenney The resource isn't fully functional yet. Still needs work. Would love your help here...

**Comment by purpleidea** [comment]
Related: https://github.com/purpleidea/mgmt/issues/97 and https://github.com/purpleidea/mgmt/issues/96

**Comment by purpleidea** [comment]
Looks like this is now FIXED in https://github.com/purpleidea/mgmt/commit/677cdea99de89572c4527406204a0a0169560bf5

Users are welcome to open new issues or PR's to add new struct features to nspawn if any are needed.

Thanks @jonathangold
