### ISSUE TITLE
implement a systemd-timers resource ("cron")

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#71]
We should probably call this cron, because we already have a "timer" resource, but we could rename that one if someone has a suggestion.

**Comment by BinaryTiger** [comment]
On it. Maybe "chrono" or "ticker" could do the job for the already existing Timer resource.

**Comment by purpleidea** [comment]
Some notes:

In probably makes sense to support different modes for time specification. I can think of three:

1) Systemd default time mode
2) Systemd calendar mode
3) Cron compatibility mode

There could be a mode value, and an input string. To transform the cron string into something systemd compatible, we could port the following code that does that to golang. https://github.com/systemd-cron/systemd-cron-next/blob/master/src/generate.rs

HTH

**Comment by daenney** [comment]
To be honest I'm not convinced we should support cron notation. Though it's been around for ages the way it works is far from obvious to most people. Every time I need it I need to go about and Google it again on how to do basic things like intervals or pick specific minutes/hours/days/weeks/months/years.

Since we're creating something new and modern perhaps we can shed some of the legacy of cron while we're at it?

**Comment by roidelapluie** [comment]
Systems timers are just services, no?

**Comment by purpleidea** [comment]
On Tue, Feb 7, 2017 at 11:27 PM, Julien Pivotto
<notifications@github.com> wrote:
>
> Systems timers are just services, no?



It's true this might be able to re-use the svc resource. I didn't look
into it. FWIW, the nspawn resource (not finished) has most of the
correct code for being a composite resource, since it uses svc to help
implement nspawn, since they are services.

Cheers

**Comment by chasen-bettinger** [comment]
@purpleidea Is there any update on this issue? Is it still desired to be implemented? I'd like to tackle it if that is the case.

**Comment by purpleidea** [comment]
This has been merged!
