### ISSUE TITLE
[LOVE] package not found on centos 7.x

### ISSUE THREAD

**Issue by erikasm** [purpleidea/mgmt#80]
cli used:
sudo ./mgmt run --file examples/pkg1.yaml --tmp-prefix

15:55:14 pkg.go:268: Pkg[powertop]: CheckApply(true)
15:55:16 pgraph.go:738: Pkg[powertop]: CheckApply errored: The FilterState method failed with: Can't find package named 'powertop'..
15:55:16 pgraph.go:881: Pkg[powertop]: Exited with failure: The FilterState method failed with: Can't find package named 'powertop'..

pkcon works:
[vagrant@testem01z1 mgmt] sudo pkcon install powertop
Resolving                     [=========================]
Querying                      [=========================]
Testing changes               [=========================]
Finished                      [=========================]
Installing                    [=========================]
Testing changes               [=========================]
Installing packages           [=========================]
Finished                      [=========================]

**Comment by purpleidea** [comment]
I didn't personally try reproducing this, but it seems as it's a legit issue on CentOS 7.x
It's probably straight forward to debug if someone wants to debug into this code.

**Comment by purpleidea** [comment]
I think the issue has to do with the package metadata not being downloaded. For example, if I do a `dnf update` on my machine, and then run mgmt, this works fine. However if I then run `dnf clean all` and run mgmt, I hit the issue. So clearly this is a bug (most likely ours, and in the pkg resource).

HTH and inspires someone to patch it?

@erikasm If you can confirm my workaround, I'd appreciate it!

**Comment by juanluisvaladas** [comment]
I'll fix this

**Comment by purpleidea** [comment]
@juanluisvaladas Awesome! Feel free to ping me if you have any questions. Either here or in #mgmtconfig IRC on Freenode.

**Comment by Spigell** [comment]
Greeting. I noticed that yum helper for packageKit try resolve package like that.
 ```
 /usr/bin/python /usr/share/PackageKit/helpers/yum/yumBackend.py resolve free;supported;newest;arch powertop
 ```
 ```
 [vagrant@localhost ~]$ sudo /usr/bin/python /usr/share/PackageKit/helpers/yum/yumBackend.py resolve "free;supported;newest;arch" powertop
 Error: No NETWORK envp
 Error: No UID envp
 Error: No BACKGROUND envp
 Error: No INTERACTIVE envp
 Loaded plugins: fastestmirror
 No plugin match for: rpm-warm-cache
 No plugin match for: auto-update-debuginfo
 No plugin match for: refresh-packagekit
 allow-cancel    false
 allow-cancel    true
 allow-cancel    true
 no-percentage-updates
 status  query
 Loading mirror speeds from cached hostfile
  * base: mirror.omnilance.com
  * epel: fedora-mirror01.rbc.ru
  * extras: mirror.omnilance.com
  * updates: mirror.omnilance.com
 finished
 ```
 I think one can't install packages because conditions are too strict. Am I wrong?
 But even if you add allowuntrusted,allownonfree and allowunsupported flags it will not be installed.
 
 
 I have added logging for result and it returns nothing. This is strange.
 
 ```
 00:21:52 pkg.go:209: &{%!s(*dbus.Conn=&{0xc820460480 0xc820435e00 true c1792aee9a64534274ebc32159a8730f [:1.36] {{0 0} 0 0 0 0} {0 0} 2 map[0:true] map[] {{0 0} 0 0 0   0} 0xc820435d40 0xc8202c4540 false {{0 0} 0 0 0 0} 0xc82035d440 <nil> {0 0}})}: BUS
 00:21:54 pkg.go:216: map[powertop:%!s(*packagekit.PkPackageIDActionData=&{false false   false})]: RESULT
 00:21:54 pkg.go:223: &{%!s(bool=false) %!s(bool=false)   %!s(bool=false)}: LOGGING
 00:21:54 pkg.go:224: %!s(bool=false): FIRST CONDITION
 00:21:54 pkg.go:225: %!s(bool=true): SECOND CONDITION
 00:52:09 main.go:533: Main: Error running auto edges: the auto edges had errors: 1 error occurred:
 * error populating file list for automatic edges: can't find package named 'powertop'
 00:52:09 main.go:415: Main: Waiting...
 
 ```
 STRACE and DEBUG vars doesn't give more information.
 On archlinux it works.
 I have tried on 1.0.7 (default one) and 1.1.5 versions of PackageKit for centos7.
 It is really cool that @juanluisvaladas will to fix it.
 
 Sorry for my English.

**Comment by purpleidea** [comment]
@Spigell I think the issue is just that this fails when the cache isn't downloaded first, since this happens if missing with the CLI tool, but I never added this to my `pkg` implementation.

I think it is cool that @juanluisvaladas will try to fix this too. I think he has some much needed dbus-skills :) Your english is just fine. let us know if you'd like to jump in and write some patches.

Thanks!

**Comment by juanluisvaladas** [comment]
Hi, @Spigell thanks for the input. It's actually very helpful.

I successfully reproduced the issue on fedora 26:
PackageKit-glib-1.1.6-2.fc26.x86_64
PackageKit-1.1.6-2.fc26.x86_64
Mgmt commit 9f66962bfb47f3d70aafb8df44ac85a40882d7f4

I'm going to work on this over the weekend
